name: WolfplzzFixes
main: com.scorchedcode.wolfplzz.Fixes.WolfplzzFixes
version: 1.0
authors: [DownToEarthDev]
description: Fixes to various issues
depend: [ProtocolLib, WorldBorder]
commands:
  deathlocation:
    usage: "/deathlocation"
    description: "Shows coords of last location you died"
    permission: wolfplzzfixes.deathlocation
  maintenance:
    usage: "/maintenance <on|off>"
    description: "Turns server maintenance mode on or off"
    permission: wolfplzzfixes.maintenance
  rtp:
    usage: "/rtp"
    description: "Teleports to a random location within the World Border"
    permission: wolfplzzfixes.rtp
  discord:
    usage: "/discord"
    description: "Displays Discord link"
  twitch:
    usage: "/twitch"
    description: "Displays Twitch link"
  website:
    usage: "/website"
    description: "Displays Website link"
  youtube:
    usage: "/youtube"
    description: "Displays Youtube link"
  teamspeak:
    usage: "/teamspeak"
    description: "Displays Teamspeak link"
permissions:
  wolfplzzfixes.maintenance:
    description: Grants ability to use maintenance mode
    default: op
  wolfplzzfixes.deathlocation:
    description: Grants ability to use /deathlocation
    default: op
  wolfplzzfixes.rtp:
    description: Grants ability to use /rtp
    default: op